:rocket: - Endpoints are ready, changed data model
tobias-le/hr-app pull request #10
Opened 2024-10-19 20:20 UTC by dmr4eg

So guys, I wrote a whole openapi specification, which closes all open tickets with endpoints creation. During this one, I discovered some strange solutions in data model that I decided to change. 

Now endpoints are working and swagger is responding.
<img width="1439" alt="Screenshot 2024-10-19 at 10 05 05 PM" src="https://github.com/user-attachments/assets/440aeb28-fa23-4f7e-9a38-fb895b524aa4">
<img width="1438" alt="Screenshot 2024-10-19 at 10 05 13 PM" src="https://github.com/user-attachments/assets/387d3ae1-7b37-45e7-93e4-7193d1c83999">
<img width="1440" alt="Screenshot 2024-10-19 at 10 05 20 PM" src="https://github.com/user-attachments/assets/e2c3d2ad-40d9-4184-a98d-c1a106b9d312">
<img width="1439" alt="Screenshot 2024-10-19 at 10 05 28 PM" src="https://github.com/user-attachments/assets/9fa6edab-2c72-4494-a4aa-8b412d8c1cb3">

2024-10-20 10:21 UTC, tobias-le reviewed
.idea do .gitignore pls

2024-10-20 10:23 UTC, tobias-le reviewed
necommituj ty vygenerovany classes, pak se to hrozne spatne reviewuje

2024-10-20 10:24 UTC, tobias-le requested changes
gitignore na vsechny .DS_Store pls

2024-10-20 10:25 UTC, tobias-le commented
Idealni pripad by bylo, kdybychom mohli pomoci mvn clean install vygenerovat open-api tridy. Neni je potreba commitovat do codebase.

2024-10-20 10:44 UTC, tobias-le commented
> Idealni pripad by bylo, kdybychom mohli pomoci mvn clean install vygenerovat open-api tridy. Neni je potreba commitovat do codebase.

Target prosim do gitignore, budeme generovat pomoci mvn clean install is all good bro

2024-10-21 14:09 UTC, nesqbo commented
mohl by sis prosim pridat ds_store do gitignore?

2024-10-21 19:13 UTC, tobias-le commented on .gitignore
> +.DS_Store
**.DS_Store lepsi ne

2024-10-21 19:13 UTC, tobias-le commented on pom.xml
> +        <springdoc.verision>2.5.0</springdoc.verision>
version*

2024-10-21 20:06 UTC, tobias-le approved these changes
approved

2024-10-22 11:32 UTC, merged